import 'package:flutter/material.dart';

const kMainColor = Color.fromRGBO(146, 95, 58, 1);
const kSecondaryColor = Color(0xff7CAC4A);
const kProductId = 'productId';
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
const kUnActiveColor = Color(0xFFC1BDB8);
const kNuts = 'nuts';
const kSpices = 'spices';
const kOils = 'oils';
const kGrain = 'grain';
const kOthers = 'others';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'Quantity';
